source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'github-pages'
gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'rake'
gem 'sass'
gem 'uglifier'
