[[redirects]]
  from = "/pgp"
  to = "https://keybase.io/thibmaek"

[[redirects]]
  from = "/github"
  to = "https://github.com/thibmaek"

[[redirects]]
  from = "/dev"
  to = "https://stackoverflow.com/users/story/3029016"
