[[redirects]]
  from = "/pgp"
  to = "https://keybase.io/thibmaek"

[[redirects]]
  from = "/github"
  to = "https://github.com/thibmaek"

[[redirects]]
  from = "/dev"
  to = "https://stackoverflow.com/users/story/3029016"

[[redirects]]
  from = "/resume"
  to = "https://www.notion.so/thibmaek/Thibault-Maekelbergh-6705f45098ee48d19a627d657fa9c67a"
